#!/bin/sh

BACKLIGHT=intel_backlight
N_STEPS=12

BRIGHTNESS_FILE=/sys/class/backlight/$BACKLIGHT/brightness
read -r BRIGHTNESS < $BRIGHTNESS_FILE
read -r MAX_BRIGHTNESS < /sys/class/backlight/$BACKLIGHT/max_brightness
STEP=$((MAX_BRIGHTNESS / $N_STEPS))
case $1 in
    down)
        NEW_BRIGHTNESS=$((BRIGHTNESS - $STEP))
        if [ $NEW_BRIGHTNESS -lt 1 ]; then
            NEW_BRIGHTNESS=1
        fi
        ;;
    up)
        NEW_BRIGHTNESS=$((BRIGHTNESS + $STEP))
        if [ $NEW_BRIGHTNESS -gt $MAX_BRIGHTNESS ]; then
            NEW_BRIGHTNESS=$MAX_BRIGHTNESS
        fi
        ;;
esac
echo $NEW_BRIGHTNESS > $BRIGHTNESS_FILE
